### ISSUE TITLE
how does this differ from sbt-version-policy?

### ISSUE THREAD

**Issue by tpolecat** [sbt/sbt-strict-update#1]
This plugin seems to do the same thing ... https://github.com/scalacenter/sbt-version-policy

**Comment by eed3si9n** [comment]
sbt-version-policy is mainly for the library authors to self-check that the library they are writing isn't in violation of the specified `versionScheme` like Semantic Versioning.

sbt-strict-update is for the app users to fail the build if their library usages break the known policies.

A closer Scala Center plugin is https://github.com/scalacenter/sbt-eviction-rules.

**Comment by tpolecat** [comment]
Oh, yes, sorry, https://github.com/scalacenter/sbt-eviction-rules is the one I intended to link. So many plugins!

Is there any important difference between yours and this one?

**Comment by eed3si9n** [comment]
Yes.
1. sbt-eviction-rules intends to improve eviction warning, so at best it displays some warning.
2. sbt-strict-update intends to burn eviction warning to the ground and replace it, and also fail `compile` task like you wanted.

**Comment by tpolecat** [comment]
Gotcha, thanks!
